<a href="https://colab.research.google.com/github/Praharshita1275/Machine-learning/blob/main/Machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}

sales_persons = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=sales_persons)

display(Sales)

            2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000

In [ ]:
# a) Display the row labels of Sales.
print("Row labels of Sales:", Sales.index)

# b) Display the column labels of Sales.
print("Column labels of Sales:", Sales.columns)

Row labels of Sales: Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')
Column labels of Sales: Index([2014, 2015, 2016, 2017], dtype='int64')

In [ ]:
# c) Display the data types of each column of Sales.
print("Data types of each column:\n", Sales.dtypes)

# d) Display the dimensions, shape, size and values of Sales.
print("\nDimensions of Sales:", Sales.ndim)
print("Shape of Sales:", Sales.shape)
print("Size of Sales:", Sales.size)
print("Values of Sales:\n", Sales.values)

Data types of each column:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object

Dimensions of Sales: 2
Shape of Sales: (5, 4)
Size of Sales: 20
Values of Sales:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]

In [ ]:
import pandas as pd

data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}

sales_persons = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=sales_persons)

data_2018 = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}

Sales2 = pd.DataFrame(data_2018)


# e) Display the last two rows of Sales.
print("Last two rows of Sales:\n", Sales.tail(2))

# f) Display the first two columns of Sales.
print("\nFirst two columns of Sales:\n", Sales.iloc[:, :2])

# a) Append the DataFrame Sales2 to the DataFrame Sales.
Sales = pd.concat([Sales, Sales2], axis=1)
print("\nSales after appending Sales2:\n", Sales)

# b) Change the DataFrame Sales such that it becomes its transpose.
Sales = Sales.T
print("\nSales after transposing:\n", Sales)

# Convert index to integer type where possible
Sales.index = pd.to_numeric(Sales.index, errors='coerce')


# c) Display the sales made by all sales persons in the year 2017.
print("\nSales made by all sales persons in 2017:\n", Sales.loc[2017])

# d) Display the sales made by Madhu and Ankit in the year 2017 and 2018.
print("\nSales made by Madhu and Ankit in 2017 and 2018:\n", Sales.loc[[2017, 2018], ['Madhu', 'Ankit']])

# e) Display the sales made by Shruti in 2016.
print("\nSales made by Shruti in 2016:\n", Sales.loc[2016, 'Shruti'])

# f) Add data to Sales for salesman Sumeet where the sales made are
# [196.2, 37800, 52000, 78438, 38852] in the years [2014, 2015, 2016, 2017, 2018] respectively.
Sales['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]
print("\nSales after adding Sumeet:\n", Sales)

# g) Create a dictionary using the following data. Use this dictionary to create a DataFrame Sales2.
# This step is already done at the beginning of the cell to ensure Sales2 is defined.

# h) Check if Sales2 is empty or it contains data.
if Sales2.empty:
    print("\nSales2 is empty.")
else:
    print("\nSales2 contains data.")

Last two rows of Sales:
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000

First two columns of Sales:
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000

Sales after appending Sales2:
             2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000

Sales after transposing:
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

Sales made by all sales persons in 2017:
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64

Sales made by Madhu and Ankit in 2017 and 2018:
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0

Sales made by Shruti in 2016:
 125000.0

Sales after adding Sumeet:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0

Sales2 contains data.

In [ ]:
import pandas as pd

data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}

sales_persons = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=sales_persons)

# a) Append the DataFrame Sales2 to the DataFrame sales.
Sales = pd.concat([Sales, Sales2], axis=1)
display(Sales)

# b) Change the DataFrame Sales such that it becomes its transpose.
Sales = Sales.T
display(Sales)

# c) Display the sales made by all sales persons in the year 2017
# Assuming Sales is transposed, the year 2017 will be a column.
print("\nSales in 2017:")
print(Sales.loc[2017])

# d) Display the sales made by Madhu and Ankit in the year 2017 and 2018.
print("\nSales made by Madhu and Ankit in 2017 and 2018:")
print("Sales Index:", Sales.index)
print("Sales Columns:", Sales.columns)
# Use boolean indexing as an alternative to .loc for multiple index labels
print(Sales[(Sales.index == 2017) | (Sales.index == 2018)][['Madhu', 'Ankit']])

# e) Display the sales made by Shruti 2016.
print("\nSales made by Shruti in 2016:")
print(Sales.loc[2016, 'Shruti'])

# f) Add data to Sales for salesman Sumeet where the sales made are [196.2, 37800, 52000, 78438, 38852] in the years [2014, 2015, 2016, 2017, 2018] respectively.
new_sales = pd.Series([196.2, 37800, 52000, 78438, 38852], index=[2014, 2015, 2016, 2017, 2018], name='Sumeet')
Sales['Sumeet'] = new_sales
display(Sales)

            2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000

         Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0

Sales in 2017:
Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64

Sales made by Madhu and Ankit in 2017 and 2018:
Sales Index: Index([2014, 2015, 2016, 2017, '2018'], dtype='object')
Sales Columns: Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')
        Madhu    Ankit
2017  50000.0  80000.0

Sales made by Shruti in 2016:
125000.0

         Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0      NaN

In [ ]:
import pandas as pd
data = {
    2014: [100.5, 150.8, 200.9, 30000, 40000],
    2015: [12000, 18000, 22000, 30000, 45000],
    2016: [20000, 50000, 70000, 100000, 125000],
    2017: [50000, 60000, 70000, 80000, 90000]
}

sales_persons = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=sales_persons)

# Append the DataFrame Sales2
Sales = pd.concat([Sales, Sales2], axis=1)

# Transpose the DataFrame
Sales = Sales.T

# Add the data for salesman Sumeet
new_sales = pd.Series([196.2, 37800, 52000, 78438, 38852], index=[2014, 2015, 2016, 2017, 2018], name='Sumeet')
Sales['Sumeet'] = new_sales


# g) Delete the data for the year 2014 from the DataFrame Sales.
Sales = Sales.drop(2014)
print(Sales)

# h) Delete the data for salesman Kinshuk from the DataFrame Sales.
Sales = Sales.drop(columns='Kinshuk')
print(Sales)

# i) Change the name of the salesperson Ankit to Vivaan and Madhu to Shailesh.
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print(Sales)

# j) Update the sale made by Shailesh in 2018 to 100000.
Sales.at[2018, 'Shailesh'] = 100000
print(Sales)

# k) Write the values of DataFrame Sales to a comma-separated file SalesFigures.csv.
# Do not write the row labels and column labels.
Sales.to_csv('SalesFigures.csv', index=False, header=False)

# l) Read the data in the file SalesFigures.csv into a DataFrame SalesRetrieved and display it.
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
print(SalesRetrieved)

# Now update the row and column labels of SalesRetrieved to match Sales.
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print(SalesRetrieved)

         Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0      NaN
         Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0      NaN
      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0      NaN
      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0      NaN
2018  100000.0       NaN       NaN       NaN      NaN
          0         1         2         3        4
0   12000.0   18000.0   30000.0   45000.0  37800.0
1   20000.0   50000.0  100000.0  125000.0  52000.0
2   50000.0   60000.0   80000.0   90000.0  78438.0
3  160000.0  110000.0  340000.0  900000.0      NaN
4  100000.0       NaN       NaN       NaN      NaN
      Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0      NaN
2018  100000.0       NaN       NaN       NaN      NaN

In [ ]:
import pandas as pd

# a) Create the DataFrame for the given table.
data = {
    'Item': ['TV', 'TV', 'TV', 'AC'],
    'Company': ['LG', 'VIDEOCON', 'LG', 'SONY'],
    'Rupees': [12000, 10000, 15000, 14000],
    'USD': [700, 650, 800, 750]
}

Product = pd.DataFrame(data)
print("Initial DataFrame:")
print(Product)

# b) Add new rows to the DataFrame.
new_data = pd.DataFrame([
    {'Item': 'AC', 'Company': 'SONY', 'Rupees': 16000, 'USD': 900},
    {'Item': 'TV', 'Company': 'SAMSUNG', 'Rupees': 17000, 'USD': 950}
])

Product = pd.concat([Product, new_data], ignore_index=True)
print("\nDataFrame after adding new rows:")
print(Product)

# c) Display the maximum price of LG TV.
lg_tv = Product[(Product['Item'] == 'TV') & (Product['Company'] == 'LG')]
max_price_lg_tv = lg_tv['Rupees'].max()
print("\nMaximum price of LG TV:", max_price_lg_tv)

# d) Display the sum of all product prices (Rupees).
total_price = Product['Rupees'].sum()
print("\nTotal sum of all product prices (Rupees):", total_price)

# e) Display the median of the USD of Sony products.
sony_products = Product[Product['Company'] == 'SONY']
median_usd_sony = sony_products['USD'].median()
print("\nMedian USD value of SONY products:", median_usd_sony)

Initial DataFrame:
  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750

DataFrame after adding new rows:
  Item   Company  Rupees  USD
0   TV        LG   12000  700
1   TV  VIDEOCON   10000  650
2   TV        LG   15000  800
3   AC      SONY   14000  750
4   AC      SONY   16000  900
5   TV   SAMSUNG   17000  950

Maximum price of LG TV: 15000

Total sum of all product prices (Rupees): 84000

Median USD value of SONY products: 825.0

In [ ]:
import pandas as pd

# a) To create the above DataFrame.
data = {
    'Name': ['Aparna', 'Pankaj', 'Ram', 'Ramesh', 'Naveen', 'Krrishnav', 'Bhawna'],
    'Degree': ['MBA', 'BCA', 'M.Tech', 'MBA', None, 'BCA', 'MBA'],
    'Score': [90.0, None, 80.0, 98.0, 97.0, 78.0, 89.0]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

# b) To print the Degree and maximum marks in each stream.
print("\nMaximum Score per Degree:")
print(df.groupby('Degree')['Score'].max())

# c) To fill the NaN values with 76.
df_filled = df.fillna(76)
print("\nDataFrame after filling NaN with 76:")
print(df_filled)

# d) To set the index to Name.
df_indexed = df.set_index('Name')
print("\nDataFrame with Name as index:")
print(df_indexed)

# e) To display the name and degree-wise average marks of each student.
print("\nAverage Score by Name and Degree:")
print(df.groupby(['Name', 'Degree'])['Score'].mean())

# f) To count the number of students in MBA.
mba_count = df[df['Degree'] == 'MBA'].shape[0]
print("\nNumber of students in MBA:", mba_count)

# g) To print the mode marks of BCA students.
bca_scores = df[df['Degree'] == 'BCA']['Score']
print("\nMode score of BCA students:", bca_scores.mode().values)

Original DataFrame:
        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA    NaN
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen    None   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0

Maximum Score per Degree:
Degree
BCA       78.0
M.Tech    80.0
MBA       98.0
Name: Score, dtype: float64

DataFrame after filling NaN with 76:
        Name  Degree  Score
0     Aparna     MBA   90.0
1     Pankaj     BCA   76.0
2        Ram  M.Tech   80.0
3     Ramesh     MBA   98.0
4     Naveen      76   97.0
5  Krrishnav     BCA   78.0
6     Bhawna     MBA   89.0

DataFrame with Name as index:
           Degree  Score
Name
Aparna        MBA   90.0
Pankaj        BCA    NaN
Ram        M.Tech   80.0
Ramesh        MBA   98.0
Naveen       None   97.0
Krrishnav     BCA   78.0
Bhawna        MBA   89.0

Average Score by Name and Degree:
Name       Degree
Aparna     MBA       90.0
Bhawna     MBA       89.0
Krrishnav  BCA       78.0
Pankaj     BCA        NaN
Ram        M.Tech    80.0
Ramesh     MBA       98.0
Name: Score, dtype: float64

Number of students in MBA: 3

Mode score of BCA students: [78.]